<a href="https://colab.research.google.com/github/najmabeegam/python/blob/main/Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [6]:
a = np.array([[10, 15]])
b = np.array([[20, 9]])
print(a)
print(b)
print()

a + b
a.T + b.T #or (a + b).T (for transpose)

[[10 15]]
[[20  9]]



array([[30],
       [24]])

In [7]:
#Substracting 2 vectors

a - b
#(a + b).T (for transpose)

array([[-10,   6]])

In [8]:
#Scalar Multiplication

a = 2
u = np.array([[30, 15]])

a * u


array([[60, 30]])

In [9]:
(a * u).T       #transpose

array([[60],
       [30]])

In [12]:
# Dot product of 2 vectors
# For 2-D vectors, it is equivalent to matrix multiplication

u = np.array([10, 20])
v = np.array([25, 6])

print(10 * 25 + 20 * 6)

np.dot(u,v)


370


np.int64(370)

In [19]:
# Matrix Addition

a = np.array([[12, 10], [4, 6], [40,31],])
b = np.array([[2, 8], [46, 63], [50,10],])


print(a, end=" = a\n\n")
print(b, end=" = b\n\n")

a + b


[[12 10]
 [ 4  6]
 [40 31]] = a

[[ 2  8]
 [46 63]
 [50 10]] = b



array([[14, 18],
       [50, 69],
       [90, 41]])

In [20]:
# Matrix Substraction
a - b

array([[ 10,   2],
       [-42, -57],
       [-10,  21]])

In [22]:
# Matrix scalar multiplication

a = 4
b = np.array([[2, 5], [3, 7], [8, 6],])

a * b

array([[ 8, 20],
       [12, 28],
       [32, 24]])

In [23]:
# Matrix and vector multiplication

a = [[5, 10], [15,20]]
b = [10, 12]

np.dot(a,b)

array([170, 390])

In [24]:
# Matrix to Matrix multiplication

a = [[5, 10], [15, 20], [25, 30]]
b = [[3, 6], [9, 5]]

np.dot(a, b)

array([[105,  80],
       [225, 190],
       [345, 300]])

In [27]:
# Transpose a matrix

a = np.array([[5, 10], [15, 20], [25,30]])
print(a, end=" = a\n\n")
print(a.T, end=" =aT")

[[ 5 10]
 [15 20]
 [25 30]] = a

[[ 5 15 25]
 [10 20 30]] =aT

In [28]:
# Identity matrix  (creates a diagonal of 1)
I1 = np.eye(2)
I2 = np.eye(3)
print(I1, end=" = I1\n\n")
print(I2, end=" = I2\n\n")

[[1. 0.]
 [0. 1.]] = I1

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] = I2

